# Inspired by https://github.com/Crascit/cmake-snap/blob/master/.travis.yml
---
language: shell
dist: xenial
os: linux

env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8
    - SNAPCRAFT_ENABLE_SILENT_REPORT: y
    - SNAPCRAFT_BUILD_INFO: 1
    - SNAPCRAFT_BUILD_ENVIRONMENT: 'lxd'

addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: classic
    - name: lxd
      channel: stable

script:
  - sudo usermod --append --groups lxd $USER
  - sudo /snap/bin/lxd.migrate -yes
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - sg lxd -c snapcraft

after_failure:
- sudo journalctl -u snapd

- stage: deploy
  if: repo = fcole90/fah-snap and branch = master
  os: linux
  deploy:
    provider: snap
    snap: folding-at-home-fcole90_*.snap
    channel: latest/stable
    cleanup: false
    skip_cleanup: true