
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  packaging_snap:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install LXD
        run: sudo snap install lxd
      
      - name: Configure LXD
        run: |
          sudo usermod --append --groups lxd $USER
          sudo /snap/bin/lxd.migrate -yes
          sudo /snap/bin/lxd waitready
          sudo /snap/bin/lxd init --auto
          
      - name: Packages
        run: echo "OK" || sg lxd -c "sudo snapcraft"